Restructuring - Itunes Provider with ItuneDetail and Itune Container
naeemdadi1/react-template pull request #7
Opened 2022-01-20 14:05 UTC by naeemdadi1

### Ticket Link

---

### Related Links

---

### Description

- Restructured folder for details page.
- Created a new folder ItunesProvider and moved itunesContainer and ituneDetailContainer in it.
- Moved selctor, saga, reducer one level up in ItunesProvider.
- Wrote Reducer, Saga, Selector and ItuneDetailContainer.

### Steps to Reproduce / Test

---

---

### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### GIF's
![feat:itunesProvider](https://user-images.githubusercontent.com/97438078/150353658-67635484-58fd-496a-a6ed-7effc8ecab65.gif)

2022-01-21 05:48 UTC, alichherawalla commented on app/components/ItunesCard/index.js
> +// import { Link } from 'react-router-dom';
remove commented out code

2022-01-28 12:38 UTC, rohan-saroha requested changes
remove the comment out code know

2022-01-29 06:35 UTC, alichherawalla commented on app/components/ItunesCard/index.js
> +      extra={<Link to={`/track/${trackId}`}>More</Link>}
please use the routeConstants

2022-01-29 06:35 UTC, alichherawalla commented on app/components/ItunesCard/tests/__snapshots__/index.test.js.snap
> +              href="/track/undefined"
add valid props for the snapshot

2022-01-29 06:37 UTC, alichherawalla approved these changes

2022-01-31 05:36 UTC, alichherawalla commented on app/utils/routeConstants.js
> +  itune: {
itunes

2022-01-31 05:36 UTC, alichherawalla commented on app/utils/routeConstants.js
> +  ituneDetail: {
itunesDetails

2022-01-31 05:38 UTC, alichherawalla commented on app/utils/routeConstants.js
> +    route: '/track/:id'
tracks

2022-01-31 06:24 UTC, merged